import time
print("kindly keep this stick safe as it is our antenna to communicate")
time.sleep(1)
print("do not disobey this order.")
time.sleep(0.5)
print("strict order")
time.sleep(2)
print("<sent by sh13pricipal>")
print(">>> /disabled teminal 101")
time.sleep(2)
print("diabling all terminal")
time.sleep(0.2)
print("DONE")
print("disable and delete location")
print('//no location has been sent')

print("terminal: 132453647586089109248sh13pr123")
time.sleep(1)
print(input("passowrd:"))
print("correct password was entered: ***2**")
print(input(">>> "))
print("invited *****c*****a****")
